#!/bin/sh

case "$1" in
    start)
        mode="664"

        # Group: since distributions do it differently, look for wheel or use staff
        if grep -q '^staff:' /etc/group; then
            group="staff"
        else
            group="wheel"
        fi

        # Load scull driver
        /sbin/insmod /lib/modules/"$(uname -r)"/extra/scull.ko || exit 1
        major=$(awk "\$2==\"scull\" {print \$1}" /proc/devices)
        rm -f /dev/scull[0-3]
        mknod /dev/scull0 c "$major" 0
        mknod /dev/scull1 c "$major" 1
        mknod /dev/scull2 c "$major" 2
        mknod /dev/scull3 c "$major" 3
        ln -sf scull0 /dev/scull
        chgrp $group /dev/scull[0-3] 
        chmod $mode  /dev/scull[0-3]

        rm -f /dev/scullpipe[0-3]
        mknod /dev/scullpipe0 c "$major" 4
        mknod /dev/scullpipe1 c "$major" 5
        mknod /dev/scullpipe2 c "$major" 6
        mknod /dev/scullpipe3 c "$major" 7
        ln -sf scullpipe0 /dev/scullpipe
        chgrp $group /dev/scullpipe[0-3] 
        chmod $mode  /dev/scullpipe[0-3]

        rm -f /dev/scullsingle
        mknod /dev/scullsingle  c "$major" 8
        chgrp $group /dev/scullsingle
        chmod $mode  /dev/scullsingle

        rm -f /dev/sculluid
        mknod /dev/sculluid   c "$major" 9
        chgrp $group /dev/sculluid
        chmod $mode  /dev/sculluid

        rm -f /dev/scullwuid
        mknod /dev/scullwuid  c "$major" 10
        chgrp $group /dev/scullwuid
        chmod $mode  /dev/scullwuid

        rm -f /dev/scullpriv
        mknod /dev/scullpriv  c "$major" 11
        chgrp $group /dev/scullpriv
        chmod $mode  /dev/scullpriv

        # Load faulty driver
        /sbin/insmod /lib/modules/"$(uname -r)"/extra/faulty.ko || exit 1
        major=$(awk "\$2==\"faulty\" {print \$1}" /proc/devices)
        rm -f /dev/faulty
        mknod /dev/faulty c "$major" 0
        chgrp $group /dev/faulty
        chmod $mode /dev/faulty

        # Load hello module
        /sbin/depmod -a
        /sbin/modprobe hello || exit 1
        ;;

    stop)
        # Remove scull driver
        /sbin/rmmod scull || exit 1
        rm -f /dev/scull /dev/scull[0-3] 
        rm -f /dev/scullpriv
        rm -f /dev/scullpipe /dev/scullpipe[0-3]
        rm -f /dev/scullsingle
        rm -f /dev/sculluid
        rm -f /dev/scullwuid

        # Remove faulty driver
        /sbin/rmmod faulty || exit 1
        rm -f /dev/faulty

        # Remove hello module
        /sbin/rmmod hello || exit 1
        ;;

    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0
